- id: 1
  name: Meta Tag Generator
  category: Tools
  price: 25000
  image: https://via.placeholder.com/300x200

- id: 2
  name: Konsultasi Terapi Relaksasi
  category: Terapis
  price: 150000
  image: https://via.placeholder.com/300x200

- id: 3
  name: Jasa Pembuatan Website
  category: Jasa
  price: 750000
  image: https://via.placeholder.com/300x200
