- name: Tool Automation
  price: 150000
  category: tools
  image: https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?q=80&w=600
  description: Software otomatisasi kerja cepat dan efisien.

- name: Jasa Service Laptop
  price: 250000
  category: jasa
  image: https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?q=80&w=600
  description: Perbaikan dan upgrade laptop profesional.
